### ISSUE TITLE
error during npm start...

### ISSUE THREAD

**Issue by ilpapabuono** [Kureev/fflux-isomorphic-example#1]
> node server.js

module.js:338
    throw err;
    ^
Error: Cannot find module 'flux/lib/invariant'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/federico/workspace/fflux-isomorphic-example/node_modules/fflux/src/Application.js:3:17)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js](/home/federico/workspace/fflux-isomorphic-example/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Any suggestion? Thanks

**Comment by ilpapabuono** [comment]
invariant.js missed under fflux/node_modules/flux/lib...
